// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import borrowing "github.com/joshuabezaleel/library-server/pkg/borrowing"
import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Borrow provides a mock function with given fields: borrow
func (_m *Repository) Borrow(borrow *borrowing.Borrow) (*borrowing.Borrow, error) {
	ret := _m.Called(borrow)

	var r0 *borrowing.Borrow
	if rf, ok := ret.Get(0).(func(*borrowing.Borrow) *borrowing.Borrow); ok {
		r0 = rf(borrow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*borrowing.Borrow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*borrowing.Borrow) error); ok {
		r1 = rf(borrow)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckBorrowed provides a mock function with given fields: bookCopyID
func (_m *Repository) CheckBorrowed(bookCopyID string) (bool, error) {
	ret := _m.Called(bookCopyID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(bookCopyID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bookCopyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: borrowID
func (_m *Repository) Get(borrowID string) (*borrowing.Borrow, error) {
	ret := _m.Called(borrowID)

	var r0 *borrowing.Borrow
	if rf, ok := ret.Get(0).(func(string) *borrowing.Borrow); ok {
		r0 = rf(borrowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*borrowing.Borrow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(borrowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserIDAndBookCopyID provides a mock function with given fields: userID, bookCopyID
func (_m *Repository) GetByUserIDAndBookCopyID(userID string, bookCopyID string) (*borrowing.Borrow, error) {
	ret := _m.Called(userID, bookCopyID)

	var r0 *borrowing.Borrow
	if rf, ok := ret.Get(0).(func(string, string) *borrowing.Borrow); ok {
		r0 = rf(userID, bookCopyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*borrowing.Borrow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, bookCopyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Return provides a mock function with given fields: borrow
func (_m *Repository) Return(borrow *borrowing.Borrow) (*borrowing.Borrow, error) {
	ret := _m.Called(borrow)

	var r0 *borrowing.Borrow
	if rf, ok := ret.Get(0).(func(*borrowing.Borrow) *borrowing.Borrow); ok {
		r0 = rf(borrow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*borrowing.Borrow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*borrowing.Borrow) error); ok {
		r1 = rf(borrow)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
