// Code generated by mockery v1.0.0. DO NOT EDIT.

package bookcopy

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: bookCopyID
func (_m *MockRepository) Delete(bookCopyID string) error {
	ret := _m.Called(bookCopyID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(bookCopyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: bookCopyID
func (_m *MockRepository) Get(bookCopyID string) (*BookCopy, error) {
	ret := _m.Called(bookCopyID)

	var r0 *BookCopy
	if rf, ok := ret.Get(0).(func(string) *BookCopy); ok {
		r0 = rf(bookCopyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BookCopy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bookCopyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: bookCopy
func (_m *MockRepository) Save(bookCopy *BookCopy) (*BookCopy, error) {
	ret := _m.Called(bookCopy)

	var r0 *BookCopy
	if rf, ok := ret.Get(0).(func(*BookCopy) *BookCopy); ok {
		r0 = rf(bookCopy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BookCopy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*BookCopy) error); ok {
		r1 = rf(bookCopy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: bookCopy
func (_m *MockRepository) Update(bookCopy *BookCopy) (*BookCopy, error) {
	ret := _m.Called(bookCopy)

	var r0 *BookCopy
	if rf, ok := ret.Get(0).(func(*BookCopy) *BookCopy); ok {
		r0 = rf(bookCopy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BookCopy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*BookCopy) error); ok {
		r1 = rf(bookCopy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
